benchmark:
  - task: rtllm
    rtllm_version: "2.0"
    path_data_benchmark:
    path_dataset_test:
    path_temporary_files: /tmp/
    path_model: /chips-design/models/
    metric_output_path: /chips-design/bigcode/results/rtllm/
    singularity_image: /chips-design/bigcode/containers/inference_images/vllm-openai-0.8.5.sif
    evaluation_image: /chips-design/bigcode/containers/evaluation_images/icarus_latest-openlane2_verilator.sif
    generate_report: True
    compute_ppl_only: False
    simulator: "verilator" # we support "icarus" or "verilator"
    models:
      - name: Qwen2.5-Coder-7B-Instruct
        multinode: False
        slurm_config: general-single-node-large
        max_length_generation: 2048
        temperature: [0.2]
        top_p: 0.95
        top_k: -1
        n_samples: 5
        swap_space: 50
        continuous_batching_size: 64
        few_shot: 0
        precision: bf16
        save_generations: True
        save_metrics: True
        save_references: False
        trust_remote_code: True
